### ISSUE TITLE
Incluir logotipo do Ministerio da Saude da Guatemala na página do país e nas telas do App

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/e-blueinfo-wp-plugin#166]
Logotipo enviado por e-mail.

**Comment by renatomurasaki** [comment]
Página do site, ok! Falta o @wilsonmoura colocar nas telas do App

**Comment by marcioalvessilva** [comment]
Segue imagem
________________________________
De: Renato Murasaki ***@***.***>
Enviado: quarta-feira, 24 de março de 2021 10:27
Para: bireme/e-blueinfo-wp-plugin ***@***.***>
Cc: Márcio Alves ***@***.***>; Assign ***@***.***>
Assunto: Re: [bireme/e-blueinfo-wp-plugin] Incluir logotipo do Ministerio da Saude da Guatemala na página do país e nas telas do App (#166)


Página do site, ok! Falta o @wilsonmoura<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fwilsonmoura&data=04%7C01%7Cdasilvmar%40paho.org%7C65919f1e3aea4d312c7108d8eec8928e%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637521892519195554%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=PNKEUU3J72vSsTujYToGteMe5lxqngS27RSRrtao16E%3D&reserved=0> colocar nas telas do App

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fe-blueinfo-wp-plugin%2Fissues%2F166%23issuecomment-805819459&data=04%7C01%7Cdasilvmar%40paho.org%7C65919f1e3aea4d312c7108d8eec8928e%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637521892519205549%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=xKNjOkZkS%2BFPMh9hCDp0e1SlpWcoqjBEFUZ6J57TPps%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FALTXRKFRGSS7ELSJ4AJQDO3TFHSD7ANCNFSM4ZVSB45Q&data=04%7C01%7Cdasilvmar%40paho.org%7C65919f1e3aea4d312c7108d8eec8928e%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637521892519215543%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=qDunvOv1jwSwKysURNgvArTfaySTEKxZPaVB0f7yjhg%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.
